
= ocp_application_validation

This role is used k8s_info module to validate OpenShift resources.


== Synopsis
* Use the k8s_info ansible module to perform read operations on K8s objects.
* Authenticate using either a config file, or password.


== Requirements
* ansible >= 2.9 
* kubernetese.core collection

== Parameters
[%autowidth,cols="^.^,^.^,^.^,",options="header"]
|===
| Parameters | Type | Default | Comments

| ocp_application_validation_file_path | path | '/tmp/validations/{{ guid[:5] \| d('common') }}/testaments' | to set directory path where validation task files will be created

| ocp_application_validation_remove_testaments | bool | true | to remove validation directory path at the end of execution

| ocp_application_validation_result_path | path | '/tmp/validations/{{ guid[:5] \| d('common') }}/' | path where results.yml will be created and file will contain validation run pass and fail. 

| ocp_application_validation_list | list | na | List of parameters for validation

.2+^.^| cluster | dict | na | dictionary of cluster parameters

  3.+a|
[cols=",,",options="header"]
!===
! Parameters ! Type ! Comments
! name ! string ! Cluster name
! host ! url ! OpenShfit console api
! username ! string ! OpenShfit cluster username
! password ! string ! OpenShfit cluster password
! onfail ! string ! Value=ignore, It ignores failed validation tasks and continues to validate other in the list. This applies to all of the validations defined under the cluster.
!===

.2+^.^| validations | list | na | Contains nested dictionary of k8s object validation
  3.+a|
[%autowidth,cols=",,",options="header"]
!===
! Parameters ! Type ! Comments
! kind ! string ! Comments
! name ! string ! Comments
! namespace ! string ! Comments
! api_version ! string ! Comments
! operator ! string ! Comments
! pipeline ! string ! Comments
! state ! string ! Comments
! retries ! string ! Comments
! delay ! string ! Comments
! conditions ! list ! Comments
! onfail ! string ! Comments
! user ! string ! Comments
! password ! string ! Comments
! force_basic_auth ! string ! Comments
! status_code ! integer ! Comments
! port ! string ! Comments
!===

|====

== Examples

[source,yaml]
----

---
- hosts: localhost
  tasks:
    - debug: 
        msg: "Test 1"

    - include_role: 
        name: ocp_application_validation
      vars:
        ocp_application_validation_list:
          - cluster:
              name: hub
              host: https://api.hub.example.com:6443
              username: username
              password: password
            validations:
             - kind: StorageCluster
               name: ocs-storagecluster
               namespace: openshift-storage
             - kind: NooBaa
               api_version: noobaa.io/v1alpha1
               name: noobaa
               namespace: openshift-storage
       
    - debug: 
        msg: "Test 2"

    - include_role: 
        name: ocp_application_validation
      vars:
        ocp_application_validation_list:
          - validations:
              - kind: Route
                name: openshift-gitops-server
                namespace: openshift-gitops

    - debug: 
        msg: "Test 3"

    - include_role: 
        name: ocp_application_validation
      vars:
        ocp_application_validation_list:
          - cluster:
              name: dev
              host: https://api.dev.example.com:6443
              username: username
              password: password
            validations:
              - kind: Route
                name: openshift-gitops-server
                namespace: openshift-gitops
----


== Authors
* Mitesh Sharma (mitsharm@redhat.com)
* Tyrell Reddy (treddy@redhat.com)
* Prakhar Srivastava (psrivast@redhat.com)
* Ritesh Shah (rshah@redhat.com)