---
- name: Log into {{ _cluster.cluster_name }} cluster 
  k8s_auth:
    host: "{{ _cluster.host }}"
    username: "{{ _cluster.username }}"
    password: "{{ _cluster.password }}"
    validate_certs: false
  register: _r_auth_cluster
  retries: 240
  delay: 15
  until:
  - _r_auth_cluster.k8s_auth.api_key is defined

- name: running validation
  when: _cluster.types is defined
  block:
    - name: validate route
      include_tasks: ./validate.yml
      loop: "{{ _cluster.types }}"
      loop_control:
        loop_var: _validate
