---
- vars:
    findme:
      - ./templates/{{ _validate.kind }}.yml.j2
      - ./templates/universal.yml.j2
  set_fact:
    _validation_file:  "{{ lookup('first_found', findme) }}"
  
- name: create testaments dir
  file:
    path: "{{ ocp_application_validation_file_path }}"
    state: directory

- name: create validation tasks file
  copy:
    content: "{{ lookup('template', _validation_file) }}"
    dest: "{{ ocp_application_validation_file_path }}/{{ _validate.kind }}.yml"
  delegate_to: localhost
     
- name: running validations
  when: _login.validations is defined
  #include_tasks: "{{ lookup('template', 'universal_test.yml.j2') | from_yaml |to_nice_yaml }}"
  include_tasks: "{{ ocp_application_validation_file_path }}/{{ _validate.kind }}.yml"