---
- name: create pre-req for validation
  delegate_to: localhost
  become: false                                                                                                                                                                                
  block:
    - name: create validation dir
      file:
        path: "{{ ocp_application_validation_file_path }}"
        state: directory
        recurse: true
        mode: 0777
   
    - name: create validation tasks file from template
      vars:
        findme:
          - ./templates/{{ _validate.kind }}.yml.j2
          - ./templates/universal.yml.j2
      template:
        src: "{{ lookup('first_found', findme)}}"
        dest: "{{ ocp_application_validation_file_path }}/{{ _v_index }}_{{_validate.kind}}.yml"
        mode: 0777
   
- name: execute validations
  when: _login.validations is defined
  include_tasks: "{{ ocp_application_validation_file_path }}/{{ _v_index }}_{{_validate.kind}}.yml"

- name: logging result
  include_tasks: log-result.yml