---
- vars:
    findme:
      - ./templates/{{ _validate.kind }}.yml.j2
      - ./templates/universal.yml.j2
  set_fact:
    object_template:  "{{ lookup('first_found', findme) }}"
  
- copy:
    content: "{{ lookup('template', object_template) }}"
    dest: /tmp/object_template.yml
  delegate_to: localhost
     
- name: running validations
  when: _login.validations is defined
  #include_tasks: "{{ lookup('template', 'universal_test.yml.j2') | from_yaml |to_nice_yaml }}"
  include_tasks: /tmp/object_template.yml