---

- name: Validate authentication
  when: _cluster.cluster_name is defined
  include_tasks: ./authentication.yml
  loop: "{{ ocp_application_validation_list }}"
  loop_control:
    loop_var: _cluster

