---
- name: using auth to log into cluster
  when:
    - _login.cluster.host is defined
    - _login.cluster.username is defined
    - _login.cluster.password is defined
    - _login.validations is defined
  block:
    - name: Log into {{ _login.cluster.host }} cluster 
      k8s_auth:
        host: "{{ _login.cluster.host }}"
        username: "{{ _login.cluster.username }}"
        password: "{{ _login.cluster.password }}"
        validate_certs: false
      register: _r_auth_cluster
      retries: 240
      delay: 15
      until:
      - _r_auth_cluster.k8s_auth.api_key is defined

    - name: set cluster auth variables
      set_fact:
        _ocp_application_validation_cluster_login_host: "{{ _r_auth_cluster.k8s_auth.host }}"
        _ocp_application_validation_cluster_login_username: "{{ _r_auth_cluster.k8s_auth.username }}"
        _ocp_application_validation_cluster_login_api_key: "{{ _r_auth_cluster.k8s_auth.api_key }}"

    - debug:
        msg: "Log into {{ _login.cluster.host }} cluster"

- name: using local .kube/config to log into cluster
  when:
    - _login.cluster.host is not defined
    - _login.cluster.username is not defined
    - _login.cluster.password is not defined
    - _login.validations is defined
  debug:
    msg: "Log into {{ _login.cluster.host }} cluster"

- name: running validations
  when: _login.validations is defined
  vars:
    findme:
      - ./testaments/{{ _validate.kind }}.yml
      - ./testaments/universal.yml
  include_tasks: "{{ lookup('first_found', findme) }}"
  loop: "{{ _login.validations }}"
  loop_control:
    loop_var: _validate
