---
- name: "[{{ _login.cluster.name |d('Cluster')}}][{{ _validate.kind }}]=> checking {{ _validate.name | d('') }}"
  k8s_info:
    host: "{{ _r_auth_cluster.k8s_auth.host | default(omit) }}"
    username: "{{ _r_auth_cluster.k8s_auth.username | default(omit) }}"
    api_key: "{{ _r_auth_cluster.k8s_auth.api_key | default(omit) }}"
    validate_certs: false
    api_version: "{{ _validate.api_version| default(omit) }}"
    kind: Route
    name: "{{ _validate.name | default(omit) }}"
    namespace: "{{ _validate.namespace | default(omit) }}"
  register: _r_validate_route
  retries: "{{ _validate.retries | default(60) }}"
  delay: "{{ _validate.delay | default(5) }}"
  until: _r_validate_route.resources | length > 0

- name: "[{{ _login.cluster.name |d('Cluster')}}][{{ _validate.kind }}]=> checking status"
  uri:
    url: "{{ _validate.port | default(_r_validate_route.resources.0.spec.port.targetPort) }}://{{ _r_validate_route.resources.0.spec.host }}"
    method: GET
    user: "{{ _validate.user |default(omit) }}"
    password: "{{ _validate.password |default(omit) }}"
    force_basic_auth: "{{ _validate.force_basic_auth |default(omit) }}"
    return_content: true
    validate_certs: false
    status_code: "{{ _validate.status_code |default(200) }}"

# _ocp4_workload_devsecops_validated_pattern_gitea_repo_globex_ui_url: >-
#       {{ r_gitea.resources[0].spec.giteaSsl | bool | ternary( 'https', 'http' ) }}://{{
#       ocp4_workload_devsecops_validated_pattern_gitea_username | urlencode }}:{{
#       ocp4_workload_devsecops_validated_pattern_gitea_password | urlencode }}@{{
#       r_gitea.resources[0].status.giteaHostname }}/{{
#       ocp4_workload_devsecops_validated_pattern_gitea_username }}/globex-ui
